services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: sit722week92d_user
      POSTGRES_PASSWORD: zNH2wx7VksKHXEnTC92qc391rKDIl0rF
      POSTGRES_DB: sit722week92d
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  book_catalog:
    build: ./book_catalog
    image: book_catalog
    environment:
      DATABASE_URL: postgresql://sit722week92d_user:zNH2wx7VksKHXEnTC92qc391rKDIl0rF@dpg-crndm4l6l47c73ae80j0-a.oregon-postgres.render.com:5432/sit722week92d
    depends_on:
      - postgres
    ports:
      - "4001:4001"

  inventory_management:
    build: ./inventory_management
    image: inventory_management
    environment:
      DATABASE_URL: postgresql://sit722week92d_user:zNH2wx7VksKHXEnTC92qc391rKDIl0rF@dpg-crndm4l6l47c73ae80j0-a.oregon-postgres.render.com:5432/sit722week92d
    depends_on:
      - postgres
    ports:
      - "4002:4002"

volumes:
  postgres_data:
