name: Deploy to AKS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Make the build-image.sh script executable
      - name: Make build-image.sh executable
        run: chmod +x ./scripts/build-image.sh

      # Make the push-image.sh script executable
      - name: Make push-image.sh executable
        run: chmod +x ./scripts/push-image.sh

      # Make the deploy.sh script executable
      - name: Make deploy.sh executable
        run: chmod +x ./scripts/deploy.sh

      # Build Docker images
      - name: Build Docker Image
        run: ./scripts/build-image.sh

      # Push Docker images to ACR
      - name: Push Docker Image
        run: ./scripts/push-image.sh

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: ./scripts/deploy.sh
