name: Deploy to AKS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.sha }}

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.6

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Apply Terraform to create infrastructure (including ACR and AKS)
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Get ACR Login URL from Terraform output
      - name: Get ACR Login URL
        id: acr_url
        run: echo "::set-output name=acr_url::$(terraform output -raw acr_login_url)"

      # Get ACR Credentials (username and password) from Terraform output
      - name: Get ACR Credentials
        id: acr_creds
        run: |
          echo "::set-output name=acr_username::$(terraform output -raw acr_username)"
          echo "::set-output name=acr_password::$(terraform output -raw acr_password)"

      # Make the build-image.sh script executable
      - name: Make build-image.sh executable
        run: chmod +x ./scripts/build-image.sh

      # Make the push-image.sh script executable
      - name: Make push-image.sh executable
        run: chmod +x ./scripts/push-image.sh

      # Make the deploy.sh script executable
      - name: Make deploy.sh executable
        run: chmod +x ./scripts/deploy.sh

      # Build Docker images
      - name: Build Docker Image
        run: ./scripts/build-image.sh
        env:
          CONTAINER_REGISTRY: ${{ steps.acr_url.outputs.acr_url }}
          VERSION: ${{ github.sha }}

      # Push Docker images to ACR
      - name: Push Docker Image
        run: ./scripts/push-image.sh
        env:
          CONTAINER_REGISTRY: ${{ steps.acr_url.outputs.acr_url }}
          VERSION: ${{ github.sha }}
          REGISTRY_UN: ${{ steps.acr_creds.outputs.acr_username }}
          REGISTRY_PW: ${{ steps.acr_creds.outputs.acr_password }}

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: ./scripts/deploy.sh
        env:
          CONTAINER_REGISTRY: ${{ steps.acr_url.outputs.acr_url }}
          VERSION: ${{ github.sha }}
